In [22]:
import numpy as np

# Сигмоида
def nonlin(x, deriv=False):
    if(deriv==True):
        return (x*(1-x))
    return 1/(1+np.exp(-x))

# набор входных данных
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

# выходные данные
y = np.array([[0,0,1,1]]).T

# сделаем случайные числа более определёнными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # насколько мы ошиблись?
    l1_error = y - l1

    # перемножим это с наклоном сигмоиды
    # на основе значений в l1
    l1_delta = l1_error * nonlin(l1,True) # !!!

    # обновим веса
    syn0 += np.dot(l0.T,l1_delta) # !!!

print ("Выходные данные после тренировки:")
print (l1)
print ('Веса:')
print (syn0)

Выходные данные после тренировки:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
Веса:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [32]:
import numpy as np

def nonlin(x, deriv=False):
    if (deriv == True):
        return (x * (1 - x))

    return 1 / (1 + np.exp(-x))


X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0
syn0 = 2 * np.random.random((2, 14)) - 1
syn1 = 2 * np.random.random((14, 1)) - 1

for j in range(60000):

    # проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))

    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2

    if (j % 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = l2_error * nonlin(l2, deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print(l2)

print (l1)


Error:0.5024705955137142
Error:0.012416831538349802
Error:0.008441694573155236
Error:0.00677035755188783
Error:0.005799104069768198
Error:0.00514690063569116
[[0.00502116]
 [0.99520558]
 [0.99555156]
 [0.00442004]]
[[5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01]
 [8.07152714e-03 6.19056435e-01 6.42274540e-03 5.40082330e-01
  8.90260476e-01 2.95137581e-01 9.59978194e-01 9.94933927e-01
  4.93004001e-01 6.13695631e-01 9.96084140e-01 9.18760029e-01
  6.66540624e-01 1.15658038e-02]
 [8.80701755e-03 5.81851004e-01 6.85781704e-03 4.43116687e-01
  1.15390224e-02 2.81829708e-01 1.32104886e-03 8.08793384e-02
  4.09392735e-01 2.54385947e-01 7.17065130e-02 9.02765423e-01
  1.91468120e-01 8.82098328e-01]
 [7.22960549e-05 6.93369964e-01 4.46348569e-05 4.83044381e-01
  8.65101812e-02 1.41126534e-01 3.07533192e-02 9.45300662e-01
  4.

In [28]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))

    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

print (l2)

[[0.00131947]
 [0.99344501]
 [0.9934567 ]
 [0.00774106]]


In [31]:
import numpy as np


# Сигмоида
def nonlin(x, deriv=False):
    if (deriv == True):
        return (x * (1 - x))
    return 1 / (1 + np.exp(-x))


# набор входных данных
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# выходные данные
y = np.array([[1, 0, 0, 1]]).T

# сделаем случайные числа более определёнными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0
syn0 = 2 * np.random.random((2, 1)) - 1

for iter in range(10000):
    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # насколько мы ошиблись?
    l1_error = y - l1

    # перемножим это с наклоном сигмоиды
    # на основе значений в l1
    l1_delta = l1_error * nonlin(l1, True)  # !!!

    # обновим веса
    syn0 += np.dot(l0.T, l1_delta)  # !!!

print ("Выходные данные после тренировки:")
print (l1)
print ('Веса:')
print (syn0)


Выходные данные после тренировки:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Веса:
[[-3.19189120e-16]
 [ 1.52655666e-16]]


In [29]:
#без скрытого слоя

import numpy as np

def nonlin(x, deriv = False):
    if(deriv == True):
        return x * (1 - x)
    return 1/(1 + np.exp(-x))

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[1, 0, 0, 1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((2, 1)) - 1

for iter in range(10000):

    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l1_error = y - l1
    l1_delta = l1_error * nonlin(l1, deriv=True)
    syn0 += np.dot(l0.T, l1_delta)

print ('Выходные данные после тренировки:')
print (l1)
print ('Веса:')
print (syn0)

Выходные данные после тренировки:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Веса:
[[-3.19189120e-16]
 [ 1.52655666e-16]]
